services:
    midnightluke.group_security.group_role_hierarchy_voter:
        class: MidnightLuke\GroupSecurityBundle\Security\GroupRoleHierarchyVoter
        tags: ['security.voter']
        arguments: ['@security.role_hierarchy']
