services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    MidnightLuke\GroupSecurityBundle\:
        resource: '../../*'
        exclude: '../../{Model,Tests}'
    Symfony\Component\Security\Core\Role\RoleHierarchyInterface:
        alias: security.role_hierarchy
